spring.application.name=ledgerly

# DB 환경 설정
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ledgerly?serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 환경 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true